
import java.awt.Font;

/*
 * PolaWyboru.java
 *
 * Created on 17 marzec 2009, 14:06
 */



/**
 *
 * @author  Armon
 */
public class PolaWyboru extends javax.swing.JFrame {

    /** Creates new form PolaWyboru */
    public PolaWyboru() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pogrubionyCheckBox = new javax.swing.JCheckBox();
        pochylonyCheckBox = new javax.swing.JCheckBox();
        tEtykieta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pogrubionyCheckBox.setText("pogrubiony");
        pogrubionyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogrubionyCheckBoxActionPerformed(evt);
            }
        });

        pochylonyCheckBox.setText("pochylony");
        pochylonyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pochylonyCheckBoxActionPerformed(evt);
            }
        });

        tEtykieta.setText("Jestem Piękna");
        tEtykieta.setFont(new Font("Monospaced", Font.PLAIN, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pogrubionyCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pochylonyCheckBox))
                    .addComponent(tEtykieta))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pochylonyCheckBox)
                    .addComponent(pogrubionyCheckBox))
                .addGap(29, 29, 29)
                .addComponent(tEtykieta)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void pogrubionyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogrubionyCheckBoxActionPerformed
    zmienStyle();
}//GEN-LAST:event_pogrubionyCheckBoxActionPerformed

private void pochylonyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pochylonyCheckBoxActionPerformed
    zmienStyle();
}//GEN-LAST:event_pochylonyCheckBoxActionPerformed

private void zmienStyle()
{
    int style = Font.PLAIN;
    
    if (pochylonyCheckBox.isSelected()) style += Font.ITALIC;
    if (pogrubionyCheckBox.isSelected()) style += Font.BOLD;
    
    tEtykieta.setFont(new Font(tEtykieta.getFont().getFamily(), style, tEtykieta.getFont().getSize()));
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaWyboru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox pochylonyCheckBox;
    private javax.swing.JCheckBox pogrubionyCheckBox;
    private javax.swing.JLabel tEtykieta;
    // End of variables declaration//GEN-END:variables

}
