
import java.awt.Font;

/*
 * Przelaczniki.java
 *
 * Created on 16 marzec 2009, 16:52
 */



/**
 *
 * @author  Armon
 */
public class Przelaczniki extends javax.swing.JFrame {

    /** Creates new form Przelaczniki */
    public Przelaczniki() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        przelacznikiRozmiaru = new javax.swing.ButtonGroup();
        malyPrzelacznik = new javax.swing.JRadioButton();
        sredniPrzelacznik = new javax.swing.JRadioButton();
        duzyPrzelacznik = new javax.swing.JRadioButton();
        tLabel = new javax.swing.JLabel();

        przelacznikiRozmiaru.add(malyPrzelacznik);
        przelacznikiRozmiaru.add(sredniPrzelacznik);
        przelacznikiRozmiaru.add(duzyPrzelacznik);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        malyPrzelacznik.setText("Mały");
        malyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malyPrzelacznikActionPerformed(evt);
            }
        });

        sredniPrzelacznik.setText("Średni");
        sredniPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sredniPrzelacznikActionPerformed(evt);
            }
        });

        duzyPrzelacznik.setText("Duży");
        duzyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzyPrzelacznikActionPerformed(evt);
            }
        });

        tLabel.setText("Coś");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(malyPrzelacznik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sredniPrzelacznik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duzyPrzelacznik))
                    .addComponent(tLabel))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duzyPrzelacznik, malyPrzelacznik, sredniPrzelacznik});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malyPrzelacznik)
                    .addComponent(sredniPrzelacznik)
                    .addComponent(duzyPrzelacznik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void sredniPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sredniPrzelacznikActionPerformed
    tLabel.setFont(new Font("Monospace", Font.ITALIC, 25));
}//GEN-LAST:event_sredniPrzelacznikActionPerformed

private void malyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malyPrzelacznikActionPerformed
    tLabel.setFont(new Font("Monospace", Font.ITALIC, 15));
}//GEN-LAST:event_malyPrzelacznikActionPerformed

private void duzyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzyPrzelacznikActionPerformed
    tLabel.setFont(new Font("Monospace", Font.ITALIC, 35));
}//GEN-LAST:event_duzyPrzelacznikActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przelaczniki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton duzyPrzelacznik;
    private javax.swing.JRadioButton malyPrzelacznik;
    private javax.swing.ButtonGroup przelacznikiRozmiaru;
    private javax.swing.JRadioButton sredniPrzelacznik;
    private javax.swing.JLabel tLabel;
    // End of variables declaration//GEN-END:variables

}
